CREATE TABLE therapist_patient_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Therapist ID, referencing the profiles table
  therapist_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Patient ID, referencing the profiles table
  patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Assignment status (e.g. 'active', 'inactive')
  status TEXT NOT NULL DEFAULT 'active',
  
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  -- Ensures that a therapist-patient pair can only exist once
  UNIQUE(therapist_id, patient_id)
);
