CREATE TABLE patient_context (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Linked 1 to 1 with the patient profile
  patient_id UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Stores initial patient information (reason for consultation, etc.)
  -- JSONB allows flexible schema without DB migrations.
  triage_info JSONB,
  
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
