CREATE TABLE conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Status: 'active' or 'completed'
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed')),
  
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  -- Updated with each message to track inactivity.
  last_message_at TIMESTAMPTZ,
  
  -- The summary of this specific conversation, generated by Flow 3.
  -- It is NULL until the offload flow processes it.
  summary TEXT,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ
);

-- Índices para consultas eficientes
CREATE INDEX idx_conversations_patient_status ON conversations(patient_id, status);
CREATE INDEX idx_conversations_last_message ON conversations(last_message_at);
