CREATE TABLE conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  -- Updated with each message to track inactivity.
  last_message_at TIMESTAMPTZ,
  
  -- The summary of this specific conversation, generated by Flow 3.
  -- It is NULL until the offload flow processes it.
  summary TEXT
);