CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Which conversation this message belongs to
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  
  sender message_sender NOT NULL,
  content TEXT NOT NULL,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
