CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Which conversation this message belongs to (can be NULL initially, resolved by trigger)
  conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
  
  -- Patient ID for direct reference (enables auto-conversation management)
  patient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  sender message_sender NOT NULL,
  content TEXT NOT NULL,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
