-- Tabla para configurar tipos de insights disponibles

CREATE TABLE insight_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Identificador único del tipo de insight
  type_key TEXT NOT NULL UNIQUE,
  
  -- Nombre descriptivo
  display_name TEXT NOT NULL,
  
  -- Si este tipo está activo para nuevas conversaciones
  is_active BOOLEAN NOT NULL DEFAULT true,
  
  -- Configuración específica del tipo (JSONB para flexibilidad)
  config JSONB DEFAULT '{}',
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Insertar los tipos de insights iniciales
INSERT INTO insight_types (type_key, display_name, config) VALUES
(
  'primary_emotions',
  'Emociones Primarias',
  '{
    "description": "Analysis of primary emotions identified in the conversation based on Ekman''s 6 basic emotions",
    "emotions": ["joy", "sadness", "anger", "fear", "surprise", "disgust"],
    "intensity_scale": [1, 10]
  }'
);

-- Índice simple
CREATE INDEX idx_insight_types_active ON insight_types(is_active);
