-- Tabla para configurar tipos de insights disponibles

CREATE TABLE insight_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Identificador único del tipo de insight
  type_key TEXT NOT NULL UNIQUE,
  
  -- Nombre descriptivo
  display_name TEXT NOT NULL,
  
  -- Si este tipo está activo para nuevas conversaciones
  is_active BOOLEAN NOT NULL DEFAULT true,
  
  -- Configuración específica del tipo (JSONB para flexibilidad)
  config JSONB DEFAULT '{}',
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Insertar los tipos de insights iniciales
INSERT INTO insight_types (type_key, display_name, config) VALUES
(
  'conversational',
  'Resumen Conversacional',
  '{
    "description": "Resumen factual de los temas y eventos discutidos en la conversación",
    "max_length": 500,
    "focus": "facts_and_topics"
  }'
),
(
  'psychological',
  'Análisis Psicológico',
  '{
    "description": "Análisis de patrones psicológicos, progreso terapéutico y recomendaciones",
    "max_length": 800,
    "focus": "therapeutic_progress",
    "include_risk_assessment": true
  }'
),
(
  'emotional',
  'Evaluación Emocional',
  '{
    "description": "Extracción de escalas emocionales y estados de ánimo reportados",
    "mood_scale_range": [1, 10],
    "extract_emotions": true
  }'
);

-- Índice simple
CREATE INDEX idx_insight_types_active ON insight_types(is_active);
