-- Tabla para almacenar insights generados

CREATE TABLE conversation_insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Conversación de la cual se genera el insight
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  
  -- Tipo de insight (referencia a insight_types)
  insight_type_id BIGINT NOT NULL REFERENCES insight_types(id),
  
  -- Estado simple: pending o completed
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
  
  -- Contenido del insight (NULL mientras esté pending)
  content JSONB,
  
  -- Timestamps básicos
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  
  -- Constraint único por conversación y tipo
  UNIQUE(conversation_id, insight_type_id)
);

-- Índices básicos
CREATE INDEX idx_insights_conversation ON conversation_insights(conversation_id);
CREATE INDEX idx_insights_status ON conversation_insights(status);
CREATE INDEX idx_insights_pending ON conversation_insights(status) WHERE status = 'pending';
